SELECT DISTINCT GIOCATORE.NOME, GIOCATORE.COGNOME
FROM GIOCATORE
NATURAL JOIN GIOCAIN
NATURAL JOIN REGISTRAZIONE
NATURAL JOIN TORNEO
WHERE GIOCATORE.Nazione ='Italia' 
AND NomeT IN ('US OPEN','Australian Open') 
AND EXTRACT (YEAR FROM (DATA1) = YEAR FROM (DATA1))
