SELECT IdG FROM GIOCAIN G1
NATURAL JOIN TORNEO T1
WHERE T1.NomeT = 'US OPEN' AND 
EXISTS (SELECT IdG FROM GIOCAIN G2
NATURAL JOIN TORNEO T2
WHERE G1.IdG = G2.IdG AND T2.NomeT = 'Australian Open' AND YEAR(T1.Data1) = YEAR(T2.Data1)
)