SELECT DISTINCT NOME,COGNOME,IdG
FROM GIOCATORE WHERE Nazione ='Italia'
AND EXIST (SELECT IdG FROM GIOCAIN NATURAL JOIN REGISTRAZIONE NATURAL JOIN TORNEO 
WHERE NomeT = 'US OPEN') AND EXIST( SELECT IdG FROM GIOCAIN NATURAL JOIN REGISTRAZIONE NATURAL JOIN TORNEO WHERE NomeT = 'Australian Open')