SELECT IDG
FROM GIOCATORE
NATURAL JOIN GIOCAIN
NATURAL JOIN REGISTRAZIONE
NATURAL JOIN TORNEO
WHERE GENERE = 'FEMMINA' AND Nazione = 'Italia' AND NomeT = 'US OPEN'
AND IDG IN (SELECT IDG
FROM GIOCATORE
NATURAL JOIN REGISTRAZIONE
NATURAL JOIN GIOCAIN
NATURAL JOIN TORNEO
WHERE GENERE = 'FEMMINA' AND Nazione = 'Italia' AND NomeT = 'Australian Open') AND (YEAR) R.REGISTRAZIONE = (YEAR) DATA.REGISTRAZIONE