SELECT DISTINCT IdG
FROM GIOCATORE NATURAL JOIN GIOCAIN NATURAL JOIN REGISTRAZIONE NATURAL JOIN TORNEO
WHERE DataF < CURRENT_DATE
AND NomeT = 'US OPEN'
AND IdG IN (
    SELECT DISTINCT IdG
    FROM GIOCATORE NATURAL JOIN GIOCAIN NATURAL JOIN REGISTRAZIONE NATURAL JOIN TORNEO
    WHERE DataF < CURRENT_DATE
    AND NomeT = 'Australian Open'
    AND DataRegistrazione = X.DataRegistrazione
);
