SELECT DISTINCT IdG
FROM GIOCATORE NATURAL JOIN GIOCAIN NATURAL JOIN REGISTRAZIONE X NATURAL JOIN TORNEO
WHERE NAZIONE = 'ITALIA'
AND NomeT = 'US Open'
AND IdG IN (
    SELECT DISTINCT IdG
    FROM GIOCATORE NATURAL JOIN REGISTRAZIONE NATURAL JOIN TORNEO
    WHERE EXTRACT(YEAR FROM DataRegistrazione) = EXTRACT(YEAR FROM X.DataRegistrazione)
    AND NomeT = 'Australian Open'
);
