SELECT DISTINCT IdG
FROM GIOCAIN NATURAL JOIN REGISTRAZIONE NATURAL JOIN TORNEO T
WHERE NomeT = 'US Open'
INTERSECT
SELECT DISTINCT IdG
FROM GIOCAIN NATURAL JOIN REGISTRAZIONE NATURAL JOIN TORNEO
WHERE NomeT = 'Australian Open' 
AND YEAR(DataI) = YEAR(T.DataI);
