SELECT IdG
FROM GIOCATORE
INNER JOIN GIOCAIN USING(IdG)
INNER JOIN TORNEO USING(IdT) AS T
WHERE NAZIONE = 'ITA' AND T.NomeT = 'US Open' AND IdG IN (
    SELECT IdG
    FROM GIOCAIN
    INNER JOIN TORNEO USING(IdT)
    WHERE NAZIONE = 'ITA' AND NomeT = 'Australian Open' 
    AND EXTRACT(YEAR FROM DataI) = EXTRACT(YEAR FROM T.DataI)
);
