SELECT IdG
FROM GIOCATORE NATURAL JOIN GIOCAIN NATURAL JOIN TORNEO X
WHERE X.NomeT = 'US Open' AND NAZIONE = 'Italia'
AND IdG IN (
    SELECT IdG
    FROM GIOCAIN NATURAL JOIN TORNEO
    WHERE NomeT = 'Australian Open' 
    AND EXTRACT(YEAR FROM DataI) = EXTRACT(YEAR FROM X.DataI)
);
