SELECT IdG, YEAR(DataI)
FROM GIOCATORE
NATURAL JOIN GIOCAIN
NATURAL JOIN TORNEO
WHERE NomeT = 'US OPEN' 
AND NAZIONE = 'GRECIA'
INTERSECT
SELECT IdG, YEAR(DataI)
FROM GIOCATORE
NATURAL JOIN GIOCAIN
NATURAL JOIN TORNEO
WHERE NomeT = 'Australian Open'
AND NAZIONE = 'GRECIA';
