SELECT IdG
FROM GIOCAIN
NATURAL JOIN REGISTRAZIONE
NATURAL JOIN TORNEO T
WHERE T.NomeT = 'US Open' 
AND EXISTS (
    SELECT IdG
    FROM GIOCAIN
    NATURAL JOIN REGISTRAZIONE
    NATURAL JOIN TORNEO
    WHERE NomeT = 'Australian Open' 
    AND DataF = T.DataF
);
