SELECT IdG, Nome, Cognome
FROM GIOCATORE
NATURAL JOIN GIOCAIN
NATURAL JOIN TORNEO
WHERE NomeT = 'US Open'
AND NAZIONE = 'GRECIA'
AND DataI = (
    SELECT DataI
    FROM GIOCAIN
    NATURAL JOIN TORNEO
    WHERE NomeT = 'Australian Open'
    AND NAZIONE = 'GRECIA'
);
