SELECT NOME
FROM PRODOTTO
WHERE IDCAT IN(
SELECT IDCAT 
FROM CATEGORIA
WHERE NOME="BEVANDE")
AND
IDPROD NOT IN (
SELECT IDPROD FROM ORDINE 
INNER JOIN DETTAGLIO_ORDINE
ON ORDINE.IDORD=DETTAGLIO_ORDINE.IDORD
WHERE EXTRACT(YEAR FROM O.data)='2023')
