SELECT PRODOTTO.nome
FROM PRODOTTO
JOIN Categoria ON ProdoTto.IDCat = Categoria.IDCat
WHERE (Categoria.nome = 'bevande'
AND PrOdOttO.IDProd
NOT IN SELECT DETTAGLIOORDINE.IDPROD
FROM DETTAGLIOORDINE
JOIN Ordine 
ON DETTAGLIOORDINE,IDORD
WHERE YEAR (Ordine.data) = '2023');
