SELECT PRODOTTO.nome
FROM PRODOTTO
JOIN Categoria ON ProdoTto.IDCat = Categoria.IDCat
WHERE (Categoria.nome = 'bevande'
AND PrOdOttO.IDProd
NOT IN SELECT DETTAGLIO_ORDINE.IDPROD
FROM DETTAGLIO_ORDINE
JOIN Ordine 
ON DETTAGLIOORDINE,IDORD
WHERE EXTRACT(YEAR FROM date) = '2023');
