SELECT PRODOTTO.nome
FROM PRODOTTO
JOIN Categoria ON ProdoTto.IDCat = Categoria.IDCat
WHERE (Categoria.nome = 'bevande'
AND PrOdOttO.IDProd
NOT IN SELECT DETTAGLIO_ORDINE.IDPROD
FROM DETTAGLIO_ORDINE
JOIN Ordine 
ON DETTAGLIO ORDINE,IDORD
WHERE YEAR (Ordine.data) = '2023');
