SELECT P.NOME FROM PRODOTTO AS P INNER JOIN CATEGORIA AS C
ON C.IDCAT = P.IDCAT
INNER JOIN DETTAGLIO_ORDINE AS D1
ON D1.IDPROD = P.IDPROD
INNER JOIN ORDINE AS O
ON O.IDORD = D1.IDORD
WHERE C.NOME = ' BEVANDE'
AND EXTRACT(YEAR FROM date) <> '2023' 
