SELECT P.NOME FROM PRODOTTO AS P INNER JOIN CATEGORIA AS C
ON C.IDCAT = P.IDCAT
INNER JOIN DETTAGLIO_ORDINE AS DO
ON DO.IDPROD = P.IDPROD
INNER JOIN ORDINE AS O
ON O.IDORD = DO.IDORD
WHERE C.NOME = ' BEVANDE'
AND YEAR (O.DATA) <> '2023' 
