SELECT P.NOME FROM PRODOTTO AS P INNER JOIN CATEGORIA AS C
ON C.IDCAT = P.IDCAT
INNER JOIN DETTAGLIOORDINE AS DO1
ON DO1.IDPROD = P.IDPROD
INNER JOIN ORDINE AS O
ON O.IDORD = DO1.IDORD
WHERE C.NOME = 'bevande'
AND EXTRACT(YEAR FROM o.data) <> '2023' 
