SELECT NOME 
FROM PRODOTTO
INNER JOIN DETTAGLIOORDINE
ON PRODTTO.IDPROD=DETTAGLIOORDINE.IDPROD
INNER JOIN CATEGORIA
ON PRODOTTO.IDCAT=CATEGORIA.IDCAT
WHERE CATEGORIA.NOME='BEVANDE'
AND
EXTRACT(YEAR FROM Ordine.data)!= 2023
