SELECT NOME 
FROM PRODOTTO
INNER JOIN DETTAGLIO_ORDINE
ON PRODTTO.IDPROD-=DETTAGLIO_ORDINE.IDPROD
INNER JOIN CATEGORIA
ON PRODOTTO.IDCAT=CATEGORIA.IDCAT
WHERE CATEGORIA.NOME='BEVANDE'
AND
YEAR(ORIDNE.DATA)!= 2023
