SELECT DISTINCT (P.NOME)
FROM PRODOTTO AS P JOIN CATEGORIA AS C ON P.IDCAT= C.IDCAT JOIN DETTAGLIO_ORDINE AS D1 ON D1.IDORD=P.IDORD
JOIN ORDINE AS O ON
O.IDORD=D1.IDORD
WhERE O.DATA <> '2023' ANO C.NOME = 'BEVANDE'
