SELECT DISTINCT (P.NOME)
FROM PRODOTTO AS P JOIN CATEGORIA AS C ON P.IDCAT= C.IDCAT JOIN DETTAGLIO_ORDINE AS DO ON DO.IDORD=P.IDORD
JOIN ORDINE AS O ON
O.IDORD=DO.IDORD
WhERE O.DATA <> '2023' ANO C.NOME = 'BEVANDE'
