SELECT DISTINCT (P.NOME)
FROM PRODOTTO AS P JOIN CATEGORIA AS C ON P.IDCAT= C.IDCAT JOIN DETTAGLIOORDINE AS DO1 ON DO1.IDORD=P.IDORD
JOIN ORDINE AS O ON
O.IDORD=DO1.IDORD
WhERE O.DATA <> '2023' AND C.NOME = 'BEVANDE'
