SELECT SUM(PREZZO*quantità) AS IMPORTO_TOTALE
FROM ORDINE
INNER JOIN DETTAGLIO_ORDINE
ON ORDINE.IDORD=DETTAGLIO_ORDINE.IDORD
INNER JOIN PRODOTTO 
ON DETTAGLIO_ORDINE.IDPROD=PRODOTTO.IDPROD
WHERE IDCLIENT='1234'
ORDER BY DATA DESC
LIMIT 1
