SELECT SUM (PRODOTTO, preZZO * DETTAGLIO_ORDINE.Quantita) A:
FROM Ordine
JOIN DETTAGLIO_ORDINE ON Ordine.IDORD = DETTAGLIO_ORDINE.IDORD
JOIN PRODOTTO ON DETTAGLIO_ORDINE.IDPROD = PRODOTTO.IDPROD
WHERE ORDINE.iDClient = '1234' 
AND Ordine.data
= (SELECT MAX (data)
FROM Ordine
WHERE IDClient= '1234');
