SELECT P.PREZZO, DO.QUANTITA FROM CLIENTE AS C
INNER JOIN ORDINE AS O
ON O.IDCLIENT = C.IDCLIENT
INNER JOIN DETTAGLIO_ORDINE AS DO
ON O.IDORD = DO.IDORD
INNER JOIN PRODOTTO AS P
ON DO.IDPROD = P.IDPROD
WHERE C.IDCLIENT = '1234'
ORDER BY O.DATA DESC
LIMIT 1
