SELECT SUM(P.PREZZO*D1.quantità)
FROM PRODOTTO AS P JOIN DETTAGLIO_ORDINE AS D1 ON D1.IDPROD=D.IDPROD
JOIN
CLIENTE AS C ON C.IDCLIENT = D1.IDCLIENT 
WHERE C.IDCLIENT= '1234'  and D1.ORD =
SELECT MAX(IDORD)
FROM DETTAGLIO_ORDINE
WHERE IDCLIENT='1234'
