SELECT SUM(P.PREZZO*DO.QUANTITÀ)
FROM PRODOTTO AS P JOIN DETTAGLIO_ORDINE AS DO ON DO.IDPROD=D.IDPROD
JOIN
CLIENTE AS C ON C.IDCLIENT = DO.IDCLIENT 
WHERE C.IDCLIENT= '1234'  ANO DO.ORD =
SELECT MAX(IDORD)
FROM DETTAGLIO_ORDINE
WHERE IDCLIENT='1234'
