SELECT DISTINCT IdG FROM GIOCATORE
NATURAL JOIN GIOCAIN
NATURAL JOIN TORNEO
NATURAL JOIN REGISTRAZIONE
WHERE Nazione = "Francia"
AND IdCat,NumRegistrazione NOT IN(SELECT DISTINCT NumRegistrazione, IdCat
FROM REGISTRAZIONE WHERE TestaDiSerie = TRUE)