SELECT IdG
FROM GIOCATORE
WHERE Nazione = "Francia" AND IdG NOT IN (SELECT IdG FROM GIOCATORE NATURAL JOIN GIOCAIN REGISTRAZIONE ON (GIOCAIN.NumRegistrazione = REGISTRAZIONE.NumRegistrazione) WHERE TestaDiSerie = TRUE)