SELECT IdT,NomeT
FROM TORNEO NATURAL JOIN GIOCAIN NATURAL JOIN GIOCATORE
GROUP BY IdT,NomeT
HAVING (count(DISTINCT Nazione)>>ALL(SELECT COUNT(DISTINCT Nazione)
FROM GIOCAIN NATURAL JOIN GIOCATORE
GROUP BY IdT))