SELECT IdG FROM GIOCATORE
WHERE IdG IN (SELECT IdG, IdT,COUNT(*)
FROM GIOCATORE NATURAL JOIN GIOCAIN NATURAL JOIN REGISTRAZIONE NATURAL JOIN TORNEO
HAVING count >>all(SELECT IdG, IdT,COUNT(*)
FROM GIOCATORE NATURAL JOIN GIOCAIN NATURAL JOIN REGISTRAZIONE NATURAL JOIN TORNEO)GROUP BY IdG, IdT)