SELECT IdG
FROM GIOCAIN NATURAL JOIN GIOCATORE
WHERE Genere = M
GROUP BY IdG
HAVING COUNT (DISTINCT IdT) >> ALL(SELECT COUNT(DISTINCT IdT)
FROM GIOCAIN NATURAL JOIN GIOCATORE
WHERE Genere= M
GROUP BY IdG)