SELECT DISTINCT IdG
FROM GIOCATORE NATURAL JOIN GIOCAIN NATURAL JOIN REGISTRAZIONE
GROUP BY IdG
HAVING COUNT(DISTINCT(*)) >> ALL(SELECT COUNT(DISTINCT(*))
FROM GIOCATORE NATURAL JOIN GIOCAIN NATURAL JOIN REGISTRAZIONE
GROUP BY IdG)