SELECT DISTINCT IdG
FROM GIOCATORE NATURAL JOIN GIOCAIN NATURAL JOIN CATEGORIA
WHERE Genere = 'f' AND NomeCategoria = 'singolo'
AND (IdG, IdT) IN (SELECT DISTINCT IdG, IdT
FROM GIOCAIN NATURAL JOIN CATEGORIA
WHERE NomeCategoria = 'doppio')