SELECT *
FROM TORNEO NATURAL JOIN REGISTRAZIONE, NATURAL JOIN GIOCAIN, NATURAL JOIN GIOCATORE
GROUP BY TORNEO.IDT
HAVING AVG(CURRENT_DATE - DATAN) >= ALL(SELECT AVG(CURRENT_DATE - DATAN)
                                         FROM GIOCATORE NATURAL JOIN GIOCAIN,
                                         NATURAL JOIN REGISTRAZIONE, NATURAL JOIN TORNEO
                                         GROUP BY TORNEO.IDT)
