SELECT NOMET, IDT
FROM TORNEO NATURAL JOIN GIOCAIN, NATURAL JOIN GIOCATORE
WHERE AVG(EXTRACT(DATE_PART(YEAR) - EXTRACT(DATE_PART(YEAR))) >= ALL
(SELECT AVG(-- --)
 FROM TORNEO NATURAL JOIN GIOCAIN, NATURAL JOIN GIOCATORE
 GROUP BY IDT)
GROUP BY IDT
