SELECT DISTINCT IDT
FROM GIOCAIN NATURAL JOIN GIOCATORE
GROUP BY IDT
HAVING AVG(DATAN) > ALL(SELECT DISTINCT AVG(DATAN)
                         FROM GIOCAIN NATURAL JOIN GIOCATORE
                         GROUP BY IDT)
