SELECT IDT 
FROM TORNEO NATURAL JOIN GIOCAIN, NATURAL JOIN GIOCATORE
GROUP BY IDT
HAVING AVG(INTERVAL_YEARS(CURRENT_DATE - DATAN)) >= ALL(SELECT AVG(INTERVAL_YEARS(CURRENT_DATE - DATAN))
                                                        FROM TORNEO NATURAL JOIN GIOCAIN, NATURAL JOIN GIOCATORE
                                                        GROUP BY IDT)
