SELECT IdG
FROM GIOCATORE
WHERE NAZIONE = 'Germania'
AND IdG NOT IN (
    SELECT IdG
    FROM GIOCATORE NATURAL JOIN GIOCAIN
    NATURAL JOIN TORNEO
    WHERE NAZIONE = 'Germania' 
    AND NomeT = 'Wimbledon'
);
