SELECT Nome, Cognome, IdG
FROM GIOCATORE
WHERE NAZIONE = "Germania"
AND IdG NOT IN (
    SELECT DISTINCT IdG
    FROM GIOCATORE
    NATURAL JOIN GIOCAIN
    NATURAL JOIN TORNEO
    WHERE NomeT = "Wimbledon"
);
