(SELECT DISTINCT IDG FROM
(SELECT IDG,IdT
FROM GIOCAIN NATURAL JOIN GIOCATORE NATURAL JOIN CATEGORIA
WHERE Genere = 'F' AND NomeCategoria = 'SINGOLI')
INTERSECT
(SELECT IDG,IdT
FROM GIOCAIN NATURAL JOIN CATEGORIA
WHERE NomeCategoria = 'POPPI'))