SELECT DISTINCT IDG
FROM GIOCAIN
NATURAL JOIN GIOCATORE
NATURAL JOIN CATEGORIA
WHERE Genere = f
AND NomeCategoria = 'SINGOLO'
AND IS IN (SELECT DISTINCT IDG
            FROM GIOCAIN
            NATURAL JOIN CATEGORIA
            WHERE IdT = X.IdT
            AND CATEGORIA = 'DOPPIO') 