SELECT * FROM GIOCATORE NATURAL JOIN GIOCAIN NATURAL JOIN REGISTRAZIONE R1 NATURAL JOIN CATEGORIA
WHERE NomeCategoria = "singoli" AND Genere = 'F' AND IdGioc IN 
(
    SELECT IdGioc FROM GIOCATORE NATURAL JOIN GIOCAIN NATURAL JOIN REGISTRAZIONE NATURAL JOIN CATEGORIA
    WHERE NomeCategoria = "doppi" AND Genere = 'F' AND R1.IdTorneo = REGISTRAZIONE.IdTorneo
);
