SELECT IDG
FROM GIOCATORE G NATURAL JOIN GIOCAIN NATURAL JOIN REGISTRAZIONE R 
NATURAL JOIN CATEGORIA
WHERE GENERE = F, NOMECATEGORIA = SINGOLI AND EXISTS 
(
    SELECT *
    FROM GIOCATORE N.JOIN GIOCAIN N.JOIN REGISTRAZIONE N.JOIN CATEGORIA
    WHERE IDG = G.IDG AND R.IDT = REGISTRAZIONE.IDT 
    AND NOMECATEGORIA = 'DOPPI'
);
