SELECT DISTINCT IdG
FROM GIOCATORE G NATURAL JOIN GIOCAIN NATURAL JOIN REGISTRAZIONE
NATURAL JOIN TORNEO TABLE
WHERE genere = 'F' AND EXISTS (SELECT * 
                               FROM REGISTRAZIONE NATURAL JOIN CATEGORIA NATURAL JOIN GIOCAIN
                               WHERE NomeCategoria = 'singolo' AND IdT = T.IdT AND IdG = G.IdG)
                               AND EXISTS (SELECT * FROM REGISTRAZIONE NATURAL JOIN CATEGORIA NATURAL JOIN GIOCAIN
                               WHERE NomeCategoria = 'doppio' AND IdT = T.IdT AND IdG = G.IdG)