SELECT G1.IdG FROM GIOCATORE G1 NATURAL JOIN GIOCAIN G1
NATURAL JOIN REGISTRAZIONE R1 NATURAL JOIN CATEGORIA C1
WHERE G1.genere = 'F' AND C1.NomeCategoria = 'singolo'
AND C2.genereCategoria = 'femmina'
AND G1.IdG IN (SELECT G2.IdG
FROM GIOCATORE G2 NATURAL JOIN REGISTRAZIONE R2
NATURAL JOIN CATEGORIA C2 
WHERE G1.IdG = G2.IdG AND G1.IdT = G2.IdT
AND C2.NomeCategoria = 'doppio')