SELECT DISTINCT G1.IdG, G1.IdT, G.Nome, G.Cognome
FROM GIOCAIN G1
JOIN GIOCAIN G2 ON G1.IdG = G2.IdG AND G1.IdT = G2.IdT
JOIN CATEGORIA C1 ON G1.IdCat = C1.IdCat
JOIN CATEGORIA C2 ON G2.IdCat = C2.IdCat
JOIN GIOCATORE G ON G1.IdG = G.IdG
WHERE C1.NomeCategoria = 'Singles'
  AND C2.NomeCategoria = 'Doubles';
