SELECT IdT, COUNT(TestaDiSerie)
FROM TORNEO
NATURAL JOIN REGISTRAZIONE
GROUP BY IdT
HAVING COUNT(TestaDiSerie) = (
    SELECT IdT, MAX(TestaDiSerie)
    FROM TORNEO
    NATURAL JOIN REGISTRAZIONE
    GROUP BY IdT
);
