SELECT IdG 
FROM TORNEI 
NATURAL GIOIN REGISTRAZIO
GROUP BY IdG, COUNT(TestaDiSerie)
HAVING COUNT(REGISTRAZIONE.TestaDiSerie) >= ALL (
    SELECT COUNT(TestaDiSerie)
    FROM TORNEO 
    JOIN NATURAL JOIN REGISTRAZIONE
    GROUP BY COUNT(TestaDiSerie)
);
