SELECT IdG
FROM GIOCATORE
NATURAL JOIN GIOCAIN
NATURAL JOIN TORNEO T
WHERE Nazione = 'Italia' AND NomeT = 'US Open'
AND IdG IN (
    SELECT IdG
    FROM GIOCAIN
    NATURAL JOIN TORNEO
    WHERE NomeT = 'Australian Open'
    AND YEAR(DataI) = YEAR(T.DataI)
);
