SELECT IdTorneo FROM TORNEO
NATURAL JOIN REGISTRAZIONE
NATURAL JOIN GIOCAIN NATURAL JOIN GIOCATORE
GROUP BY IdTorneo, Nazione
HAVING COUNT(DISTINCT Nazione) >=ALL (SELECT COUNT(
    DISTINCT Nazione) FROM TORNEO NATURAL JOIN REGISTRAZIONE NATURAL JOIN GIOCAIN NATURAL JOIN GIOCATORE)
    GROUP BY IdTorneo,Nazione
