SELECT IdT
FROM TORNEO NATURAL JOIN REGISTRAZIONE NATURAL JOIN
GIOCAIN NATURAL JOIN GIOCATORE GROUP BY IdT
HAVING COUNT(Nazione) >=
ALL(SELECT COUNT(DISTINCT Nazione)
FROM TORNEO NATURAL JOIN REGISTRAZIONE NATURAL JOIN GIOCATORE)


