SELECT IdT,Nazione
FROM TORNEO NATURAL JOIN GIOCAIN NATURAL JOIN GIOCATORE
GROUP BY Nazione
HAVING COUNT(*) >=ALL(SELECT COUNT(Nazione),IdT,Nazione
FROM TORNEO NATURAL JOIN GIOCAIN NATURAL JOIN GIOCATORE
GROUP BY Nazione)