SELECT IdT
FROM TORNEO NATURAL JOIN REGISTRAZIONE NATURAL JOIN GIOCAIN
NATURAL JOIN GIOCATORE
GROUP BY IdT,Nazione
HAVING COUNT(*) >> ALL(SELECT COUNT(*)
FROM TORNEO NATURAL JOIN REGISTRAZIONE NATURAL JOIN GIOCAIN
NATURAL JOIN GIOCATORE
GROUP BY IdT, Nazione)