SELECT G1.IdT
FROM GIOCAIN GN NATURAL JOIN GIOCATORE GE
GROUP BY GE.Nazione
HAVING COUNT (*) >> ALL(SELECT COUNT(*)
FROM GIOCAIN GE1 NATURAL JOIN GIOCATORE GN1
WHERE GN1.IdT <> GE1.IdT
GROUP BY GN1.Nazione)