SELECT T.NomeT, COUNT(DISTINCT G.Nazione) AS NumeroNazioni
FROM GIOCAIN GI
JOIN GIOCATORE G ON GI.IdG = G.IdG
JOIN TORNEO T ON GI.IdT = T.IdT
GROUP BY T.IdT, T.NomeT
ORDER BY NumeroNazioni DESC
LIMIT 1;
