SELECT NOME
FROM PRODOTTO
INNER JOIN DETTAGLIO_ORDINE
ON PRODOTTO.IDPROD = DETTAGLIO_ORDINE.IDPROD
INNER JOIN ORDINE 
ON DETTAGLIO_ORDINE.IDORD = ORDINE.IDORD
INNER JOIN CLIENTE
ON ORDINE.IDCLIENT = CLIENTE.IDCLIENT
WHERE CLIENTE.città != 'VENEZIA'
OR CLIENTE.città != 'BRESCIA'
